apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs-pv
  storageClassName: jenkins-nfs-sc
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/kubernetes/jenkins
    server: 192.168.0.96
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-nfs-pvc
  storageClassName: jenkins-nfs-sc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  volumes:
    - name: jenkins-pvc
      persistentVolumeClaim:
        claimName: jenkins-nfs-pvc
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts-jdk17
      ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000
      volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: jenkins-pvc