apiVersion: v1
kind: Deployment
metadata:
  name: jenkins-deploy
  namespace: jenkins
spec:
  replicas: 1
  volumes:
    - name: jenkins-pvc
      persistentVolumeClaim:
        claimName: jenkins-nfs-pvc
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts-jdk17
      ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000
      volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: jenkins-pvc
