apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs-pv
spec:
  storageClassName: jenkins-nfs-sc
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/kubernetes/jenkins
    server: 192.168.0.96
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-nfs-pvc
spec:
  storageClassName: jenkins-nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
